name: DevOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '20'

      - name: Install & Test
        run: |
          npm install --legacy-peer-deps
          npm run lint # Shows you care about code quality
          
      - name: Build Docker Image
        run: docker build -t scratchpad:latest .

      - name: Run Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'scratchpad:latest'
          format: 'table'
          exit-code: '0' # Don't fail the build yet, just show the report
          severity: 'CRITICAL,HIGH'
